---
title: "Schedule"
---

| Date                 | Topic                 | Lecture                                                        | Slides                                                                           | HW                                                         |                        Projects |
|:---------------------|:----------------------|:---------------------------------                              |:------------                                                                     |:------------                                               |                     -----------:|
| Tues Sept 5          | What is Data Science? | [What is Data Science?](what_is_ds_i.html)                     | [<i class="fas fa-desktop fa-lg"></i>](slides/what_is_data_science_i.pdf)        | [<i class="far fa-file-code fa-lg"></i>](homework_0.html)  |                                 |   
| Thur Sept 7          | Building blocks       | [Best Practices](best_practices.html)                          | [<i class="fas fa-desktop fa-lg"></i>](slides/best_practices.pdf)                |                                                            |                                 |
| Tues Sept 12         | Building blocks       | [Writing with Data](writing_with_data.html)                    | [<i class="fas fa-desktop fa-lg"></i>](slides/writing_with_data.pdf)             |                                                            |                                 |
| Thur Sept 14         | Building blocks       | [Git](git.html)                                                | [<i class="fas fa-desktop fa-lg"></i>](slides/git_and_github.pdf)                | [<i class="far fa-file-code fa-lg"></i>](homework_1.html)  |                                 |   
| Tues Sept 19         | Data Wrangling I      | [Data Import](data_import.html)                                | [<i class="fas fa-desktop fa-lg"></i>](slides/data_import.pdf)                   |                                                            |                                 | 
| Thur Sept 21         | Data Wrangling I      | [Data Manipulation](data_manipulation.html)                    | [<i class="fas fa-desktop fa-lg"></i>](slides/data_manipulation.pdf)             |                                                            |                                 | 
| Tues Sept 26         | Data Wrangling I      | [Tidy data](tidy_data.html)                                    | [<i class="fas fa-desktop fa-lg"></i>](slides/tidy_data.pdf)                     | [<i class="far fa-file-code fa-lg"></i>](homework_2.html)  |                                 |    
| Thur Sept 28         | Viz + EDA             | [Visualization 1](visualization_pt1.html)                      | [<i class="fas fa-desktop fa-lg"></i>](slides/visualization.pdf)                 |                                                            |                                 | 
| Tues Oct 3           | Viz + EDA             | [Visualization 2](visualization_pt2.html)                      | [<i class="fas fa-desktop fa-lg"></i>](slides/visualization.pdf)                 |                                                            |                                 | 
| Thur Oct 5           | Viz + EDA             | [EDA](exploratory_analysis.html)                               | [<i class="fas fa-desktop fa-lg"></i>](slides/exploratory_analysis.pdf)          | [<i class="far fa-file-code fa-lg"></i>](homework_3.html)  |                                 |    
| Tues Oct 10          | Case Study            | [Case study](what_is_ds_ii.html)                               | [<i class="fas fa-desktop fa-lg"></i>](slides/what_is_data_science_ii.pdf)       |                                                            |                                 | 
| Thur Oct 12          | Data Wrangling II     | [Reading Data from the Web](reading_data_from_the_web.html)    | [<i class="fas fa-desktop fa-lg"></i>](slides/reading_data_from_the_web.pdf)     |                                                            |                                 | 
| Tues Oct 17          | Data Wrangling II     | [Strings and Factors](strings_and_factors.html)                | [<i class="fas fa-desktop fa-lg"></i>](slides/strings_and_factors.pdf)           |                                                            | [Midterm](midterm_project.html) | 
| Thur Oct 19          | Interactivity         | [Making Websites](making_websites.html)                        | [<i class="fas fa-desktop fa-lg"></i>](slides/making_websites.pdf)               |                                                            |                                 | 
| Tues Oct 24          | Interactivity         | [Plot.ly and Dashboards](plotly_and_dashboards.html)           | [<i class="fas fa-desktop fa-lg"></i>](slides/plotly_and_dashboards.pdf)         | [<i class="far fa-file-code fa-lg"></i>](homework_4.html)  | [Final](final_project.html)     | 
| Thur Oct 26          | Iteration             | [Writing Functions](writing_functions.html)                    | [<i class="fas fa-desktop fa-lg"></i>](slides/writing_functions.pdf)             |                                                            |                                 | 
| Tues Oct 31          | Iteration             | [Iteration and Listcols](iteration_and_listcols.html)          | [<i class="fas fa-desktop fa-lg"></i>](slides/iteration_and_listcols.pdf)        |                                                            |                                 | 
| Thur Nov 2           | Iteration             | [Simulation](simulation.html)                                  | [<i class="fas fa-desktop fa-lg"></i>](slides/simulation.pdf)                    | [<i class="far fa-file-code fa-lg"></i>](homework_5.html)  |                                 | 
| Tues Nov 7           | -Election day-        |                                                                |                                                                                  |                                                            |                                 | 
| Thur Nov 9           | Linear models         | [Linear Models](linear_models.html)                            | [<i class="fas fa-desktop fa-lg"></i>](slides/linear_models.pdf)                 |                                                            |                                 | 
| Tues Nov 14          | Linear models         | [Cross Validation](cross_validation.html)                      | [<i class="fas fa-desktop fa-lg"></i>](slides/cross_validation.pdf)              |                                                            |                                 | 
| Thur Nov 16          | Linear models         | [Bootstrapping](bootstrapping.html)                            | [<i class="fas fa-desktop fa-lg"></i>](slides/bootstrapping.pdf)                 | [<i class="far fa-file-code fa-lg"></i>](homework_6.html)  |                                 | 
| Tues Nov 21          | -Thanksgiving-        |                                                                |                                                                                  |                                                            |                                 | 
| Thur Nov 23          | -Thanksgiving-        |                                                                |                                                                                  |                                                            |                                 | 
| Tues Nov 28          | Extra topics          | [Shiny apps](shiny.html)                                       | [<i class="fas fa-desktop fa-lg"></i>](slides/shiny.pdf)                         |                                                            |                                 |  
| Thur Nov 30          | Extra topics          | [Statistical Learning](stat_learning.html)                     | [<i class="fas fa-desktop fa-lg"></i>](slides/stat_learning.pdf)                 | [<i class="far fa-file-code fa-lg"></i>](homework_7.html)  |                                 |  
| Tues Dec 5           | -Final Project Week-  |                                                                |                                                                                  |                                                            |                                 | 
| Thur Dec 7           | -Final Project Week-  |                                                                |                                                                                  |                                                            |                                 | 
| Thur Dec 14          | Final Projects!       | [What is Data Science Revisited](what_is_ds_iii.html)          | [<i class="fas fa-desktop fa-lg"></i>](slides/what_is_data_science_iii.pdf)      |                                                            |                                 |
 